
builds:

- id: puccini-tosca
  main: ./executables/puccini-tosca
  binary: puccini-tosca
  goarch:
  - amd64
  - wasm
  goos:
  - linux
  - darwin
  - windows
  - js
  ldflags:
  - -X 'github.com/tliron/go-kutil/version.GitVersion={{.Env.VERSION}}'
  - -X 'github.com/tliron/go-kutil/version.GitRevision={{.Env.REVISION}}'
  - -X 'github.com/tliron/go-kutil/version.Timestamp={{.Env.TIMESTAMP}}'

- id: puccini-clout
  main: ./executables/puccini-clout
  binary: puccini-clout
  goarch:
  - amd64
  - wasm
  goos:
  - linux
  - darwin
  - windows
  - js
  ldflags:
  - -X 'github.com/tliron/go-kutil/version.GitVersion={{.Env.VERSION}}'
  - -X 'github.com/tliron/go-kutil/version.GitRevision={{.Env.REVISION}}'
  - -X 'github.com/tliron/go-kutil/version.Timestamp={{.Env.TIMESTAMP}}'

- id: puccini-csar
  main: ./executables/puccini-csar
  binary: puccini-csar
  goarch:
  - amd64
  - wasm
  goos:
  - linux
  - darwin
  - windows
  - js
  ldflags:
  - -X 'github.com/tliron/go-kutil/version.GitVersion={{.Env.VERSION}}'
  - -X 'github.com/tliron/go-kutil/version.GitRevision={{.Env.REVISION}}'
  - -X 'github.com/tliron/go-kutil/version.Timestamp={{.Env.TIMESTAMP}}'

nfpms:

- formats:
  - rpm
  - deb
  homepage: https://github.com/tliron/go-puccini
  maintainer: Tal Liron <tal.liron@gmail.com>
  description: Deliberately stateless cloud topology management and deployment tools based on TOSCA.
  license: Apache 2.0

archives:

- files:
  - README.md
  - LICENSE
  - NOTICE
  - assets/tosca/**/*
  - examples/**/*

  format_overrides:
  - goos: windows
    format: zip

checksum:

  name_template: checksums.txt

release:

  #disable: true
  #prerelease: true

  github:
    owner: tliron
    name: go-puccini
